jwt:
  secret: "GfH9j1/ZQ4g9cQh3PQV2mRupzP3vB6fJ4qFq1xTzp0A6qX6Jk9kBAQ=="
  access-token-expiration: 1440 # 1 día

frontend:
  url: ${FRONTEND_URL}

app:
  url: ${APP_URL}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}
