spring:
  application:
    name: rescue bites

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    open-in-view: false

  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 40MB

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: simple

  profiles:
    active: ${SPRING_PROFILE:development}

  data:
    web:
      pageable:
        one-indexed-parameters: false
      rest:
        page-parameter-name: page
        size-parameter-name: size
        sort-parameter-name: sort

frontend:
  url: ${FRONTEND_URL}

app:
  url: ${APP_URL}
  default-profile-picture: ${DEFAULT_PROFILE_PICTURE_URL}

payment:
  redirect:
    success-url: ${PAYMENT_REDIRECT_SUCCESS_URL}
    failure-url: ${PAYMENT_REDIRECT_FAILURE_URL}
    pending-url: ${PAYMENT_REDIRECT_PENDING_URL}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.mail: DEBUG
    com.rescuebites.api: INFO

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:default_secret}
  access-token-expiration: ${JWT_EXPIRATION:86400000}